### ISSUE TITLE
Issue with API call

### ISSUE THREAD

**Issue by Deadlyelder** [AaltoAsia/O-MI-Authorization#1]
Hello,

I have the modules up and running but whenever any the API call is attempted the following error is returned

```bash
HTTP/1.1 404 Not Found
Content-Length: 42
Content-Type: text/plain; charset=UTF-8
...
Server: akka-http/10.1.1

The requested resource could not be found.
```

Furthermore, there is no error logged on the server side. Am I missing something?

Regards

**Comment by TK009** [comment]
Hi,
Did you notice that we changed the url to start with `/v1/` ?

**Comment by Deadlyelder** [comment]
Good Morning,

Yes, I noticed the base path set towards `/v1` within the swagger file and as such have also tested it with `.../v1/...`.

The error is still the same.

**Comment by TK009** [comment]
Ok, I fixed the problem, thanks for reporting!
