### ISSUE TITLE
API call for retrieving all users and groups

### ISSUE THREAD

**Issue by Deadlyelder** [AaltoAsia/O-MI-Authorization#2]
It would be good to have the following API calls, for troubleshooting/debugging purpose:

* `/get-users`
> Return back the list of users who have been registered.

* `/get-groups`
> Return the list of available groups.

**Comment by TK009** [comment]
I agree, this is a planned feature

**Comment by Deadlyelder** [comment]
Great!

Meanwhile, where can I access the raw access-control database for verification? (I might have stumbled across a bug but want to cross-check in the raw database first ;))

**Comment by TK009** [comment]
You can use this http://www.h2database.com/html/tutorial.html#shell_tool or change the db to something more familiar in the application.conf

**Comment by TK009** [comment]
The name and location of db was a bit silly, so I changed it in 777ab91

**Comment by TK009** [comment]
These have been added in 39f3c33f2bd8e357df48798a05a73e6a548907cf, needs tests

**Comment by Deadlyelder** [comment]
Thanks testing it.

**Comment by TK009** [comment]
merged to master
