### ISSUE TITLE
Issue setting permission to group after update

### ISSUE THREAD

**Issue by Deadlyelder** [AaltoAsia/O-MI-Authorization#3]
Not sure if the changes broke the database but some issues:

* The old users, groups and permission seems to be lost after update _Likely due to changed database name_
* Created new user `Alice`, new group named `Sims`, `Alice` added towards the group and permission for the groups are set. Later the call for `get-permission` returns empty permissions as result...

```bash
HTTP/1.1 200 OK
...
{
 "allowed": [],
 "denied": [],
}
```

**Comment by TK009** [comment]
did you add Alice to the group with join-groups?

**Comment by TK009** [comment]
I could not reproduce this. Could you provide exact commands to reproduce this bug. I tried following commands with `httpie` that follows your description closely:

```
http POST :8001/v1/add-user username=Alice
http POST :8001/v1/add-group groupname=Sims
http POST :8001/v1/join-groups username=Alice groups:='["Sims"]'
http POST :8001/v1/set-rules group=Sims rules:='[{"path":"Objects","request":"r","allow":true}]'
http POST :8001/v1/get-permissions username=Alice request=r
```

All commands returned `200 OK` and the result of last one was:
```
HTTP/1.1 200 OK
Content-Length: 35
Content-Type: application/json
Date: Fri, 22 Jun 2018 06:59:22 GMT
Server: akka-http/10.1.1

{
    "allowed": [
        "Objects"
    ],
    "denied": []
}
```

**Comment by TK009** [comment]
You can recover the old db by `mv ./logs/sensorDB.h2.mv.db database.h2.mv.db`

**Comment by Deadlyelder** [comment]
My bad, it was typo error :( Had FR keyboard.

Thanks
